macro(_check_file_exists file)
	if(NOT EXISTS "${file}" )
		message(FATAL_ERROR "The file \"${file}\" does not exist.")
	endif()
endmacro()

macro(_populate_target_props TargetName Configuration LIB_LOCATION IMPLIB_LOCATION)
	# Seems a relative directory is not working using REALPATH.
	get_filename_component(imported_location "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/${LIB_LOCATION}" REALPATH)
	#set(imported_location "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/${LIB_LOCATION}")
	_check_file_exists(${imported_location})
	set_target_properties(${TargetName} PROPERTIES "IMPORTED_LOCATION_${Configuration}" ${imported_location})
	if(NOT "${IMPLIB_LOCATION}" STREQUAL "")
		set(imported_implib "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/${IMPLIB_LOCATION}")
		_check_file_exists(${imported_implib})
		set_target_properties(${TargetName} PROPERTIES "IMPORTED_IMPLIB_${Configuration}" ${imported_implib})
	endif()
endmacro()

macro(_add_shared_library TargetName)
	# When the target does not exists add it.
	if (NOT TARGET ${TargetName})
		message(STATUS "Adding library: ${TargetName}")
		add_library(${TargetName} SHARED IMPORTED)
		if (WIN32)
			_populate_target_props(${TargetName} DEBUG "lib${TargetName}.dll" "lib${TargetName}.dll.a")
		else()
			_populate_target_props(${TargetName} DEBUG "lib${TargetName}.so" "")
		endif()
	endif()
endmacro()
