# Create variable holding the libraries filename.
set(TargetName "sf-misc")
# When the target exists ignore it.
if (TARGET ${TargetName})
	#message(STATUS "Target '${PROJECT_NAME}': Library '${TargetName}' is already part of build.")
else ()
	message(STATUS "Target '${PROJECT_NAME}': Adding library '${TargetName}'.")
	add_library(${TargetName} SHARED IMPORTED ../misc/gen/TPointer.h ../misc/gen/TSet.h)
	if (WIN32)
		_populate_target_props(${TargetName} DEBUG "lib${TargetName}.dll" "lib${TargetName}.dll.a")
	else ()
		_populate_target_props(${TargetName} DEBUG "lib${TargetName}.so" "")
	endif ()
	get_filename_component(_include_location "${CMAKE_CURRENT_LIST_DIR}/.." REALPATH)
	set_property(TARGET ${TargetName} PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${_include_location}")
endif ()
